// micro-react/app.jsx
import React, { useState } from 'react';
import './index.css';

export default function App() {
  const [count, setCount] = useState(0);
  return (
    <div>
      react app
      <div>
        counr: {count}
        <button onClick={() => setCount(count + 1)}>+1</button>
      </div>
    </div>
  )
}

// example/vue2.6/app.vue
<template>
<div>
  vue app
  <div class="counter">
    counr: {{count}}
    <button @click="setCount(count + 1)">+1</button>
  </div>
</div>
</template>
<script>
export default {
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    setCount(count) {
      this.count = count;
    },
  },
}
</script>
<style>
body {
  background: #ddd
}
</style>
